apiVersion: apps/v1
kind: Deployment
metadata:
  name: income-classifier
  labels:
    app: income-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: income-classifier
  template:
    metadata:
      labels:
        app: income-classifier
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: income-classifier
        image: kanishka76/income-classifier:1.0.3
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"