name: ML Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy dvc[dagshub] xgboost

      - name: Pull data from DagsHub
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user Kanishka-Msd
          dvc remote modify origin --local password $DAGSHUB_TOKEN
          dvc pull --remote origin

      - name: Run pipeline
        run: |
          dvc repro
      - name: Generate metrics report
        run: |
          python src/evaluate.py

      - name: Post CML report
        uses: iterative/setup-cml@v2

      - name: Comment metrics on commit
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create metrics_report.md